//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace TestWebProj.Data
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class BankingAppEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new BankingAppEntities object using the connection string found in the 'BankingAppEntities' section of the application configuration file.
        /// </summary>
        public BankingAppEntities() : base("name=BankingAppEntities", "BankingAppEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new BankingAppEntities object.
        /// </summary>
        public BankingAppEntities(string connectionString) : base(connectionString, "BankingAppEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new BankingAppEntities object.
        /// </summary>
        public BankingAppEntities(EntityConnection connection) : base(connection, "BankingAppEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Command> Command
        {
            get
            {
                if ((_Command == null))
                {
                    _Command = base.CreateObjectSet<Command>("Command");
                }
                return _Command;
            }
        }
        private ObjectSet<Command> _Command;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Employee> Employee
        {
            get
            {
                if ((_Employee == null))
                {
                    _Employee = base.CreateObjectSet<Employee>("Employee");
                }
                return _Employee;
            }
        }
        private ObjectSet<Employee> _Employee;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<LoanSchedule> LoanSchedule
        {
            get
            {
                if ((_LoanSchedule == null))
                {
                    _LoanSchedule = base.CreateObjectSet<LoanSchedule>("LoanSchedule");
                }
                return _LoanSchedule;
            }
        }
        private ObjectSet<LoanSchedule> _LoanSchedule;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Menu> Menu
        {
            get
            {
                if ((_Menu == null))
                {
                    _Menu = base.CreateObjectSet<Menu>("Menu");
                }
                return _Menu;
            }
        }
        private ObjectSet<Menu> _Menu;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<MenuProperty> MenuProperty
        {
            get
            {
                if ((_MenuProperty == null))
                {
                    _MenuProperty = base.CreateObjectSet<MenuProperty>("MenuProperty");
                }
                return _MenuProperty;
            }
        }
        private ObjectSet<MenuProperty> _MenuProperty;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Property> Property
        {
            get
            {
                if ((_Property == null))
                {
                    _Property = base.CreateObjectSet<Property>("Property");
                }
                return _Property;
            }
        }
        private ObjectSet<Property> _Property;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PropertyCommand> PropertyCommand
        {
            get
            {
                if ((_PropertyCommand == null))
                {
                    _PropertyCommand = base.CreateObjectSet<PropertyCommand>("PropertyCommand");
                }
                return _PropertyCommand;
            }
        }
        private ObjectSet<PropertyCommand> _PropertyCommand;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Role> Role
        {
            get
            {
                if ((_Role == null))
                {
                    _Role = base.CreateObjectSet<Role>("Role");
                }
                return _Role;
            }
        }
        private ObjectSet<Role> _Role;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<RoleCommand> RoleCommand
        {
            get
            {
                if ((_RoleCommand == null))
                {
                    _RoleCommand = base.CreateObjectSet<RoleCommand>("RoleCommand");
                }
                return _RoleCommand;
            }
        }
        private ObjectSet<RoleCommand> _RoleCommand;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<RoleMenu> RoleMenu
        {
            get
            {
                if ((_RoleMenu == null))
                {
                    _RoleMenu = base.CreateObjectSet<RoleMenu>("RoleMenu");
                }
                return _RoleMenu;
            }
        }
        private ObjectSet<RoleMenu> _RoleMenu;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblAccounts> tblAccounts
        {
            get
            {
                if ((_tblAccounts == null))
                {
                    _tblAccounts = base.CreateObjectSet<tblAccounts>("tblAccounts");
                }
                return _tblAccounts;
            }
        }
        private ObjectSet<tblAccounts> _tblAccounts;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblTransaction> tblTransaction
        {
            get
            {
                if ((_tblTransaction == null))
                {
                    _tblTransaction = base.CreateObjectSet<tblTransaction>("tblTransaction");
                }
                return _tblTransaction;
            }
        }
        private ObjectSet<tblTransaction> _tblTransaction;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<User> User
        {
            get
            {
                if ((_User == null))
                {
                    _User = base.CreateObjectSet<User>("User");
                }
                return _User;
            }
        }
        private ObjectSet<User> _User;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<UserRole> UserRole
        {
            get
            {
                if ((_UserRole == null))
                {
                    _UserRole = base.CreateObjectSet<UserRole>("UserRole");
                }
                return _UserRole;
            }
        }
        private ObjectSet<UserRole> _UserRole;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<MenuView> MenuView
        {
            get
            {
                if ((_MenuView == null))
                {
                    _MenuView = base.CreateObjectSet<MenuView>("MenuView");
                }
                return _MenuView;
            }
        }
        private ObjectSet<MenuView> _MenuView;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<RoleProperty> RoleProperty
        {
            get
            {
                if ((_RoleProperty == null))
                {
                    _RoleProperty = base.CreateObjectSet<RoleProperty>("RoleProperty");
                }
                return _RoleProperty;
            }
        }
        private ObjectSet<RoleProperty> _RoleProperty;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Command EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCommand(Command command)
        {
            base.AddObject("Command", command);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Employee EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEmployee(Employee employee)
        {
            base.AddObject("Employee", employee);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the LoanSchedule EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLoanSchedule(LoanSchedule loanSchedule)
        {
            base.AddObject("LoanSchedule", loanSchedule);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Menu EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMenu(Menu menu)
        {
            base.AddObject("Menu", menu);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the MenuProperty EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMenuProperty(MenuProperty menuProperty)
        {
            base.AddObject("MenuProperty", menuProperty);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Property EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProperty(Property property)
        {
            base.AddObject("Property", property);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PropertyCommand EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPropertyCommand(PropertyCommand propertyCommand)
        {
            base.AddObject("PropertyCommand", propertyCommand);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Role EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRole(Role role)
        {
            base.AddObject("Role", role);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the RoleCommand EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRoleCommand(RoleCommand roleCommand)
        {
            base.AddObject("RoleCommand", roleCommand);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the RoleMenu EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRoleMenu(RoleMenu roleMenu)
        {
            base.AddObject("RoleMenu", roleMenu);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblAccounts EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblAccounts(tblAccounts tblAccounts)
        {
            base.AddObject("tblAccounts", tblAccounts);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblTransaction EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblTransaction(tblTransaction tblTransaction)
        {
            base.AddObject("tblTransaction", tblTransaction);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the User EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUser(User user)
        {
            base.AddObject("User", user);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the UserRole EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUserRole(UserRole userRole)
        {
            base.AddObject("UserRole", userRole);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the MenuView EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMenuView(MenuView menuView)
        {
            base.AddObject("MenuView", menuView);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the RoleProperty EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRoleProperty(RoleProperty roleProperty)
        {
            base.AddObject("RoleProperty", roleProperty);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BankingAppModel", Name="Command")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Command : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Command object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static Command CreateCommand(global::System.Int64 id)
        {
            Command command = new Command();
            command.ID = id;
            return command;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CommandName
        {
            get
            {
                return _CommandName;
            }
            set
            {
                OnCommandNameChanging(value);
                ReportPropertyChanging("CommandName");
                _CommandName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CommandName");
                OnCommandNameChanged();
            }
        }
        private global::System.String _CommandName;
        partial void OnCommandNameChanging(global::System.String value);
        partial void OnCommandNameChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BankingAppModel", Name="Employee")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Employee : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Employee object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static Employee CreateEmployee(global::System.Int64 id)
        {
            Employee employee = new Employee();
            employee.ID = id;
            return employee;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Designation
        {
            get
            {
                return _Designation;
            }
            set
            {
                OnDesignationChanging(value);
                ReportPropertyChanging("Designation");
                _Designation = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Designation");
                OnDesignationChanged();
            }
        }
        private global::System.String _Designation;
        partial void OnDesignationChanging(global::System.String value);
        partial void OnDesignationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> ManagerID
        {
            get
            {
                return _ManagerID;
            }
            set
            {
                OnManagerIDChanging(value);
                ReportPropertyChanging("ManagerID");
                _ManagerID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ManagerID");
                OnManagerIDChanged();
            }
        }
        private Nullable<global::System.Int64> _ManagerID;
        partial void OnManagerIDChanging(Nullable<global::System.Int64> value);
        partial void OnManagerIDChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BankingAppModel", Name="LoanSchedule")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class LoanSchedule : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new LoanSchedule object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static LoanSchedule CreateLoanSchedule(global::System.Int64 id)
        {
            LoanSchedule loanSchedule = new LoanSchedule();
            loanSchedule.ID = id;
            return loanSchedule;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LoanAccountNo
        {
            get
            {
                return _LoanAccountNo;
            }
            set
            {
                OnLoanAccountNoChanging(value);
                ReportPropertyChanging("LoanAccountNo");
                _LoanAccountNo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LoanAccountNo");
                OnLoanAccountNoChanged();
            }
        }
        private global::System.String _LoanAccountNo;
        partial void OnLoanAccountNoChanging(global::System.String value);
        partial void OnLoanAccountNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> InstallmentNo
        {
            get
            {
                return _InstallmentNo;
            }
            set
            {
                OnInstallmentNoChanging(value);
                ReportPropertyChanging("InstallmentNo");
                _InstallmentNo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("InstallmentNo");
                OnInstallmentNoChanged();
            }
        }
        private Nullable<global::System.Int32> _InstallmentNo;
        partial void OnInstallmentNoChanging(Nullable<global::System.Int32> value);
        partial void OnInstallmentNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> EMIDate
        {
            get
            {
                return _EMIDate;
            }
            set
            {
                OnEMIDateChanging(value);
                ReportPropertyChanging("EMIDate");
                _EMIDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EMIDate");
                OnEMIDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _EMIDate;
        partial void OnEMIDateChanging(Nullable<global::System.DateTime> value);
        partial void OnEMIDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> BegningBalance
        {
            get
            {
                return _BegningBalance;
            }
            set
            {
                OnBegningBalanceChanging(value);
                ReportPropertyChanging("BegningBalance");
                _BegningBalance = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BegningBalance");
                OnBegningBalanceChanged();
            }
        }
        private Nullable<global::System.Double> _BegningBalance;
        partial void OnBegningBalanceChanging(Nullable<global::System.Double> value);
        partial void OnBegningBalanceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> SchedulePaymentAmt
        {
            get
            {
                return _SchedulePaymentAmt;
            }
            set
            {
                OnSchedulePaymentAmtChanging(value);
                ReportPropertyChanging("SchedulePaymentAmt");
                _SchedulePaymentAmt = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SchedulePaymentAmt");
                OnSchedulePaymentAmtChanged();
            }
        }
        private Nullable<global::System.Double> _SchedulePaymentAmt;
        partial void OnSchedulePaymentAmtChanging(Nullable<global::System.Double> value);
        partial void OnSchedulePaymentAmtChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> PrincipalAmt
        {
            get
            {
                return _PrincipalAmt;
            }
            set
            {
                OnPrincipalAmtChanging(value);
                ReportPropertyChanging("PrincipalAmt");
                _PrincipalAmt = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PrincipalAmt");
                OnPrincipalAmtChanged();
            }
        }
        private Nullable<global::System.Double> _PrincipalAmt;
        partial void OnPrincipalAmtChanging(Nullable<global::System.Double> value);
        partial void OnPrincipalAmtChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> InterestAmt
        {
            get
            {
                return _InterestAmt;
            }
            set
            {
                OnInterestAmtChanging(value);
                ReportPropertyChanging("InterestAmt");
                _InterestAmt = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("InterestAmt");
                OnInterestAmtChanged();
            }
        }
        private Nullable<global::System.Double> _InterestAmt;
        partial void OnInterestAmtChanging(Nullable<global::System.Double> value);
        partial void OnInterestAmtChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> PaidAmt
        {
            get
            {
                return _PaidAmt;
            }
            set
            {
                OnPaidAmtChanging(value);
                ReportPropertyChanging("PaidAmt");
                _PaidAmt = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PaidAmt");
                OnPaidAmtChanged();
            }
        }
        private Nullable<global::System.Double> _PaidAmt;
        partial void OnPaidAmtChanging(Nullable<global::System.Double> value);
        partial void OnPaidAmtChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> PrincipalPaid
        {
            get
            {
                return _PrincipalPaid;
            }
            set
            {
                OnPrincipalPaidChanging(value);
                ReportPropertyChanging("PrincipalPaid");
                _PrincipalPaid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PrincipalPaid");
                OnPrincipalPaidChanged();
            }
        }
        private Nullable<global::System.Double> _PrincipalPaid;
        partial void OnPrincipalPaidChanging(Nullable<global::System.Double> value);
        partial void OnPrincipalPaidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> InterestPaid
        {
            get
            {
                return _InterestPaid;
            }
            set
            {
                OnInterestPaidChanging(value);
                ReportPropertyChanging("InterestPaid");
                _InterestPaid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("InterestPaid");
                OnInterestPaidChanged();
            }
        }
        private Nullable<global::System.Double> _InterestPaid;
        partial void OnInterestPaidChanging(Nullable<global::System.Double> value);
        partial void OnInterestPaidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> OverDueAmount
        {
            get
            {
                return _OverDueAmount;
            }
            set
            {
                OnOverDueAmountChanging(value);
                ReportPropertyChanging("OverDueAmount");
                _OverDueAmount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OverDueAmount");
                OnOverDueAmountChanged();
            }
        }
        private Nullable<global::System.Double> _OverDueAmount;
        partial void OnOverDueAmountChanging(Nullable<global::System.Double> value);
        partial void OnOverDueAmountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> PricipalOverDue
        {
            get
            {
                return _PricipalOverDue;
            }
            set
            {
                OnPricipalOverDueChanging(value);
                ReportPropertyChanging("PricipalOverDue");
                _PricipalOverDue = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PricipalOverDue");
                OnPricipalOverDueChanged();
            }
        }
        private Nullable<global::System.Double> _PricipalOverDue;
        partial void OnPricipalOverDueChanging(Nullable<global::System.Double> value);
        partial void OnPricipalOverDueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> InterestOverDue
        {
            get
            {
                return _InterestOverDue;
            }
            set
            {
                OnInterestOverDueChanging(value);
                ReportPropertyChanging("InterestOverDue");
                _InterestOverDue = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("InterestOverDue");
                OnInterestOverDueChanged();
            }
        }
        private Nullable<global::System.Double> _InterestOverDue;
        partial void OnInterestOverDueChanging(Nullable<global::System.Double> value);
        partial void OnInterestOverDueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> AdvanceAmount
        {
            get
            {
                return _AdvanceAmount;
            }
            set
            {
                OnAdvanceAmountChanging(value);
                ReportPropertyChanging("AdvanceAmount");
                _AdvanceAmount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AdvanceAmount");
                OnAdvanceAmountChanged();
            }
        }
        private Nullable<global::System.Double> _AdvanceAmount;
        partial void OnAdvanceAmountChanging(Nullable<global::System.Double> value);
        partial void OnAdvanceAmountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> PrincepalAdvance
        {
            get
            {
                return _PrincepalAdvance;
            }
            set
            {
                OnPrincepalAdvanceChanging(value);
                ReportPropertyChanging("PrincepalAdvance");
                _PrincepalAdvance = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PrincepalAdvance");
                OnPrincepalAdvanceChanged();
            }
        }
        private Nullable<global::System.Double> _PrincepalAdvance;
        partial void OnPrincepalAdvanceChanging(Nullable<global::System.Double> value);
        partial void OnPrincepalAdvanceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> InterestAdvance
        {
            get
            {
                return _InterestAdvance;
            }
            set
            {
                OnInterestAdvanceChanging(value);
                ReportPropertyChanging("InterestAdvance");
                _InterestAdvance = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("InterestAdvance");
                OnInterestAdvanceChanged();
            }
        }
        private Nullable<global::System.Double> _InterestAdvance;
        partial void OnInterestAdvanceChanging(Nullable<global::System.Double> value);
        partial void OnInterestAdvanceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.String _Status;
        partial void OnStatusChanging(global::System.String value);
        partial void OnStatusChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BankingAppModel", Name="Menu")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Menu : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Menu object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static Menu CreateMenu(global::System.Int64 id)
        {
            Menu menu = new Menu();
            menu.ID = id;
            return menu;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MenuName
        {
            get
            {
                return _MenuName;
            }
            set
            {
                OnMenuNameChanging(value);
                ReportPropertyChanging("MenuName");
                _MenuName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MenuName");
                OnMenuNameChanged();
            }
        }
        private global::System.String _MenuName;
        partial void OnMenuNameChanging(global::System.String value);
        partial void OnMenuNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> ParentID
        {
            get
            {
                return _ParentID;
            }
            set
            {
                OnParentIDChanging(value);
                ReportPropertyChanging("ParentID");
                _ParentID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ParentID");
                OnParentIDChanged();
            }
        }
        private Nullable<global::System.Int64> _ParentID;
        partial void OnParentIDChanging(Nullable<global::System.Int64> value);
        partial void OnParentIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MenuOrder
        {
            get
            {
                return _MenuOrder;
            }
            set
            {
                OnMenuOrderChanging(value);
                ReportPropertyChanging("MenuOrder");
                _MenuOrder = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MenuOrder");
                OnMenuOrderChanged();
            }
        }
        private Nullable<global::System.Int32> _MenuOrder;
        partial void OnMenuOrderChanging(Nullable<global::System.Int32> value);
        partial void OnMenuOrderChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BankingAppModel", Name="MenuProperty")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MenuProperty : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new MenuProperty object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static MenuProperty CreateMenuProperty(global::System.Int64 id)
        {
            MenuProperty menuProperty = new MenuProperty();
            menuProperty.ID = id;
            return menuProperty;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MenuName
        {
            get
            {
                return _MenuName;
            }
            set
            {
                OnMenuNameChanging(value);
                ReportPropertyChanging("MenuName");
                _MenuName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MenuName");
                OnMenuNameChanged();
            }
        }
        private global::System.String _MenuName;
        partial void OnMenuNameChanging(global::System.String value);
        partial void OnMenuNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PropertyName
        {
            get
            {
                return _PropertyName;
            }
            set
            {
                OnPropertyNameChanging(value);
                ReportPropertyChanging("PropertyName");
                _PropertyName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PropertyName");
                OnPropertyNameChanged();
            }
        }
        private global::System.String _PropertyName;
        partial void OnPropertyNameChanging(global::System.String value);
        partial void OnPropertyNameChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BankingAppModel", Name="MenuView")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MenuView : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new MenuView object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static MenuView CreateMenuView(global::System.Int64 id)
        {
            MenuView menuView = new MenuView();
            menuView.ID = id;
            return menuView;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MenuName
        {
            get
            {
                return _MenuName;
            }
            set
            {
                OnMenuNameChanging(value);
                ReportPropertyChanging("MenuName");
                _MenuName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MenuName");
                OnMenuNameChanged();
            }
        }
        private global::System.String _MenuName;
        partial void OnMenuNameChanging(global::System.String value);
        partial void OnMenuNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> ParentID
        {
            get
            {
                return _ParentID;
            }
            set
            {
                OnParentIDChanging(value);
                ReportPropertyChanging("ParentID");
                _ParentID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ParentID");
                OnParentIDChanged();
            }
        }
        private Nullable<global::System.Int64> _ParentID;
        partial void OnParentIDChanging(Nullable<global::System.Int64> value);
        partial void OnParentIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MenuOrder
        {
            get
            {
                return _MenuOrder;
            }
            set
            {
                OnMenuOrderChanging(value);
                ReportPropertyChanging("MenuOrder");
                _MenuOrder = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MenuOrder");
                OnMenuOrderChanged();
            }
        }
        private Nullable<global::System.Int32> _MenuOrder;
        partial void OnMenuOrderChanging(Nullable<global::System.Int32> value);
        partial void OnMenuOrderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PropertyName
        {
            get
            {
                return _PropertyName;
            }
            set
            {
                OnPropertyNameChanging(value);
                ReportPropertyChanging("PropertyName");
                _PropertyName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PropertyName");
                OnPropertyNameChanged();
            }
        }
        private global::System.String _PropertyName;
        partial void OnPropertyNameChanging(global::System.String value);
        partial void OnPropertyNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RoleName
        {
            get
            {
                return _RoleName;
            }
            set
            {
                OnRoleNameChanging(value);
                ReportPropertyChanging("RoleName");
                _RoleName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RoleName");
                OnRoleNameChanged();
            }
        }
        private global::System.String _RoleName;
        partial void OnRoleNameChanging(global::System.String value);
        partial void OnRoleNameChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BankingAppModel", Name="Property")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Property : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Property object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static Property CreateProperty(global::System.Int64 id)
        {
            Property property = new Property();
            property.ID = id;
            return property;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PropertyName
        {
            get
            {
                return _PropertyName;
            }
            set
            {
                OnPropertyNameChanging(value);
                ReportPropertyChanging("PropertyName");
                _PropertyName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PropertyName");
                OnPropertyNameChanged();
            }
        }
        private global::System.String _PropertyName;
        partial void OnPropertyNameChanging(global::System.String value);
        partial void OnPropertyNameChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BankingAppModel", Name="PropertyCommand")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PropertyCommand : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PropertyCommand object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static PropertyCommand CreatePropertyCommand(global::System.Int64 id)
        {
            PropertyCommand propertyCommand = new PropertyCommand();
            propertyCommand.ID = id;
            return propertyCommand;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PropertyName
        {
            get
            {
                return _PropertyName;
            }
            set
            {
                OnPropertyNameChanging(value);
                ReportPropertyChanging("PropertyName");
                _PropertyName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PropertyName");
                OnPropertyNameChanged();
            }
        }
        private global::System.String _PropertyName;
        partial void OnPropertyNameChanging(global::System.String value);
        partial void OnPropertyNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CommandName
        {
            get
            {
                return _CommandName;
            }
            set
            {
                OnCommandNameChanging(value);
                ReportPropertyChanging("CommandName");
                _CommandName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CommandName");
                OnCommandNameChanged();
            }
        }
        private global::System.String _CommandName;
        partial void OnCommandNameChanging(global::System.String value);
        partial void OnCommandNameChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BankingAppModel", Name="Role")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Role : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Role object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static Role CreateRole(global::System.Int64 id)
        {
            Role role = new Role();
            role.ID = id;
            return role;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RoleName
        {
            get
            {
                return _RoleName;
            }
            set
            {
                OnRoleNameChanging(value);
                ReportPropertyChanging("RoleName");
                _RoleName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RoleName");
                OnRoleNameChanged();
            }
        }
        private global::System.String _RoleName;
        partial void OnRoleNameChanging(global::System.String value);
        partial void OnRoleNameChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BankingAppModel", Name="RoleCommand")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class RoleCommand : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new RoleCommand object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static RoleCommand CreateRoleCommand(global::System.Int64 id)
        {
            RoleCommand roleCommand = new RoleCommand();
            roleCommand.ID = id;
            return roleCommand;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RoleName
        {
            get
            {
                return _RoleName;
            }
            set
            {
                OnRoleNameChanging(value);
                ReportPropertyChanging("RoleName");
                _RoleName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RoleName");
                OnRoleNameChanged();
            }
        }
        private global::System.String _RoleName;
        partial void OnRoleNameChanging(global::System.String value);
        partial void OnRoleNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CommandName
        {
            get
            {
                return _CommandName;
            }
            set
            {
                OnCommandNameChanging(value);
                ReportPropertyChanging("CommandName");
                _CommandName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CommandName");
                OnCommandNameChanged();
            }
        }
        private global::System.String _CommandName;
        partial void OnCommandNameChanging(global::System.String value);
        partial void OnCommandNameChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BankingAppModel", Name="RoleMenu")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class RoleMenu : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new RoleMenu object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static RoleMenu CreateRoleMenu(global::System.Int64 id)
        {
            RoleMenu roleMenu = new RoleMenu();
            roleMenu.ID = id;
            return roleMenu;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MenuName
        {
            get
            {
                return _MenuName;
            }
            set
            {
                OnMenuNameChanging(value);
                ReportPropertyChanging("MenuName");
                _MenuName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MenuName");
                OnMenuNameChanged();
            }
        }
        private global::System.String _MenuName;
        partial void OnMenuNameChanging(global::System.String value);
        partial void OnMenuNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RoleName
        {
            get
            {
                return _RoleName;
            }
            set
            {
                OnRoleNameChanging(value);
                ReportPropertyChanging("RoleName");
                _RoleName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RoleName");
                OnRoleNameChanged();
            }
        }
        private global::System.String _RoleName;
        partial void OnRoleNameChanging(global::System.String value);
        partial void OnRoleNameChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BankingAppModel", Name="RoleProperty")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class RoleProperty : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new RoleProperty object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static RoleProperty CreateRoleProperty(global::System.Int64 id)
        {
            RoleProperty roleProperty = new RoleProperty();
            roleProperty.ID = id;
            return roleProperty;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PropertyName
        {
            get
            {
                return _PropertyName;
            }
            set
            {
                OnPropertyNameChanging(value);
                ReportPropertyChanging("PropertyName");
                _PropertyName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PropertyName");
                OnPropertyNameChanged();
            }
        }
        private global::System.String _PropertyName;
        partial void OnPropertyNameChanging(global::System.String value);
        partial void OnPropertyNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RoleName
        {
            get
            {
                return _RoleName;
            }
            set
            {
                OnRoleNameChanging(value);
                ReportPropertyChanging("RoleName");
                _RoleName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RoleName");
                OnRoleNameChanged();
            }
        }
        private global::System.String _RoleName;
        partial void OnRoleNameChanging(global::System.String value);
        partial void OnRoleNameChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BankingAppModel", Name="tblAccounts")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblAccounts : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblAccounts object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static tblAccounts CreatetblAccounts(global::System.Int64 id)
        {
            tblAccounts tblAccounts = new tblAccounts();
            tblAccounts.ID = id;
            return tblAccounts;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AccountType
        {
            get
            {
                return _AccountType;
            }
            set
            {
                OnAccountTypeChanging(value);
                ReportPropertyChanging("AccountType");
                _AccountType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AccountType");
                OnAccountTypeChanged();
            }
        }
        private global::System.String _AccountType;
        partial void OnAccountTypeChanging(global::System.String value);
        partial void OnAccountTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AccountName
        {
            get
            {
                return _AccountName;
            }
            set
            {
                OnAccountNameChanging(value);
                ReportPropertyChanging("AccountName");
                _AccountName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AccountName");
                OnAccountNameChanged();
            }
        }
        private global::System.String _AccountName;
        partial void OnAccountNameChanging(global::System.String value);
        partial void OnAccountNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AccountNumber
        {
            get
            {
                return _AccountNumber;
            }
            set
            {
                OnAccountNumberChanging(value);
                ReportPropertyChanging("AccountNumber");
                _AccountNumber = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AccountNumber");
                OnAccountNumberChanged();
            }
        }
        private global::System.String _AccountNumber;
        partial void OnAccountNumberChanging(global::System.String value);
        partial void OnAccountNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsActive
        {
            get
            {
                return _IsActive;
            }
            set
            {
                OnIsActiveChanging(value);
                ReportPropertyChanging("IsActive");
                _IsActive = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsActive");
                OnIsActiveChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsActive;
        partial void OnIsActiveChanging(Nullable<global::System.Boolean> value);
        partial void OnIsActiveChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BankingAppModel", Name="tblTransaction")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblTransaction : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblTransaction object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static tblTransaction CreatetblTransaction(global::System.Int64 id)
        {
            tblTransaction tblTransaction = new tblTransaction();
            tblTransaction.ID = id;
            return tblTransaction;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AccountNo
        {
            get
            {
                return _AccountNo;
            }
            set
            {
                OnAccountNoChanging(value);
                ReportPropertyChanging("AccountNo");
                _AccountNo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AccountNo");
                OnAccountNoChanged();
            }
        }
        private global::System.String _AccountNo;
        partial void OnAccountNoChanging(global::System.String value);
        partial void OnAccountNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TxnType
        {
            get
            {
                return _TxnType;
            }
            set
            {
                OnTxnTypeChanging(value);
                ReportPropertyChanging("TxnType");
                _TxnType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TxnType");
                OnTxnTypeChanged();
            }
        }
        private global::System.String _TxnType;
        partial void OnTxnTypeChanging(global::System.String value);
        partial void OnTxnTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Amount
        {
            get
            {
                return _Amount;
            }
            set
            {
                OnAmountChanging(value);
                ReportPropertyChanging("Amount");
                _Amount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Amount");
                OnAmountChanged();
            }
        }
        private Nullable<global::System.Double> _Amount;
        partial void OnAmountChanging(Nullable<global::System.Double> value);
        partial void OnAmountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _Date;
        partial void OnDateChanging(Nullable<global::System.DateTime> value);
        partial void OnDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Balance
        {
            get
            {
                return _Balance;
            }
            set
            {
                OnBalanceChanging(value);
                ReportPropertyChanging("Balance");
                _Balance = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Balance");
                OnBalanceChanged();
            }
        }
        private Nullable<global::System.Double> _Balance;
        partial void OnBalanceChanging(Nullable<global::System.Double> value);
        partial void OnBalanceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CrDr
        {
            get
            {
                return _CrDr;
            }
            set
            {
                OnCrDrChanging(value);
                ReportPropertyChanging("CrDr");
                _CrDr = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CrDr");
                OnCrDrChanged();
            }
        }
        private global::System.String _CrDr;
        partial void OnCrDrChanging(global::System.String value);
        partial void OnCrDrChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Particular
        {
            get
            {
                return _Particular;
            }
            set
            {
                OnParticularChanging(value);
                ReportPropertyChanging("Particular");
                _Particular = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Particular");
                OnParticularChanged();
            }
        }
        private global::System.String _Particular;
        partial void OnParticularChanging(global::System.String value);
        partial void OnParticularChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BankingAppModel", Name="User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class User : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new User object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static User CreateUser(global::System.Int64 id)
        {
            User user = new User();
            user.ID = id;
            return user;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BankingAppModel", Name="UserRole")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class UserRole : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new UserRole object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static UserRole CreateUserRole(global::System.Int64 id)
        {
            UserRole userRole = new UserRole();
            userRole.ID = id;
            return userRole;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RoleName
        {
            get
            {
                return _RoleName;
            }
            set
            {
                OnRoleNameChanging(value);
                ReportPropertyChanging("RoleName");
                _RoleName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RoleName");
                OnRoleNameChanged();
            }
        }
        private global::System.String _RoleName;
        partial void OnRoleNameChanging(global::System.String value);
        partial void OnRoleNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();

        #endregion

    
    }

    #endregion

    
}
